version: '3'
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./jup:/home/jovyan/work
    ports:
      - '8888:8888'
  db_pg:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123
volumes:
  pgdata:
  jup: